# Generated by Django 4.2.16 on 2024-12-06 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='table_choice',
            field=models.CharField(choices=[('8:00-9:00', '8:00-9:00'), ('9:00-10:00', '9:00-10:00'), ('10:00-11:00', '10:00-11:00'), ('11:00-12:00', '11:00-12:00')], default='8:00-9:00'),
        ),
        migrations.AddField(
            model_name='booking',
            name='table_type',
            field=models.CharField(choices=[('1', 'A small table, with enough room for two, coffees and games'), ('2', 'A slightly larger table, with plenty of room for coffees, cakes and games'), ('3', 'A purpose buily gaming table with a great deal of room for those lucky/unlucky rolls!')], default='1'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_of_guests',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
    ]
