# Generated by Django 4.2.16 on 2024-12-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0002_booking_table_choice_booking_table_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='table_choice',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='booking',
            name='table_type',
            field=models.CharField(choices=[('1', 'A small table, with enough room for two, coffees and games'), ('2', 'A slightly larger table, with plenty of room for coffees, cakes and games'), ('3', 'A purpose built gaming table with a great deal of room for those lucky/unlucky rolls!')], default='1'),
        ),
    ]
