# Generated by Django 4.2.16 on 2024-12-06 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0003_rename_table_choice_booking_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table_type',
            field=models.CharField(choices=[('1', 'A small and cosy table, with enough room for two, coffees and games'), ('2', 'A slightly larger table, with plenty of room for coffees, cakes and games - suitable for about 2-3 players'), ('3', 'A purpose built gaming table with a great deal of room for those lucky/unlucky rolls!'), ('4', 'A huge gaming table with hidden drawers for cards and areas to roll dice seen or unseen!')], default='1'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('12pm-2pm', '12pm-2pm'), ('1pm-3pm', '1pm-3pm'), ('2pm-4pm', '2pm-4pm'), ('3pm-5pm', '3pm-5pm'), ('4pm-6pm', '4pm-6pm'), ('5pm-7pm', '5pm-7pm')], default='8:00-9:00'),
        ),
    ]
