# Generated by Django 4.2.16 on 2025-01-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0005_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourite_game',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
