# Generated by Django 4.2.16 on 2025-01-04 17:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0006_userprofile_favourite_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=autoslug.fields.AutoSlugField(max_length=70, null=True, unique=True),
        ),
    ]
